function [guiPRT] = IHM_frame1(STRUCT_PRT)
% *************************************************************************
%   Name :   IHM_frame1
%   Date of creation : 21/10/2021
%   Description : Creation of the menus in the main window
% *************************************************************************

Parent = STRUCT_PRT.figure.START.panel_ihm;
num_figure = STRUCT_PRT.figure.num_figure;
PanelColor = [0.815686274509804	0.878431372549020 0.921568627450980];

%% Principal Panel
guiPRT.framePanel_up = uipanel(Parent,...
    'visible','on',...
    'BackgroundColor',PanelColor,...
    'Title', ('Initialization'),...
    'FontSize',11,...
    'position',[0 0.35 1.*1/0.86 1-0.35]);

guiPRT.framePanel_down = uipanel(Parent,...
    'visible','on',...
    'BackgroundColor',PanelColor,...
    'Title', ('Alignement'),...
    'FontSize',11,...
    'position',[0 0 1.*1/0.86 0.35]);

%% INITIALIZATION
% Validation
guiPRT.Validation_button = uicontrol(guiPRT.framePanel_up,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'position',[0.31 0.07 0.15 0.14],...
    'Callback',{@IHM_frame1_CB,num_figure,'Validation'},...
    'Value',0,...
    'String','Valider');

% Red rectangle
guiPRT.Rectangle = uicontrol(guiPRT.framePanel_up,...
    'style','text',...
    'units','normalized',...
    'FontSize',9,...
    'BackgroundColor','red',...
    'Visible','on',...
    'Position',[0.48 0.07 0.08 0.14]);

%%
Pos = 0.74;
Length_edit = 0.2;
Height_edit = 0.10;
PosX_edit = 0.23;
PosX_text = 0.035;
Alignement = 'Left';
%%
% Oscilloscope port
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment',Alignement,...
    'position',[PosX_text Pos 0.15 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Port oscilloscope');

% Oscilloscope edit box
guiPRT.Oscillo_port = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame1_CB,num_figure,'Oscillo_port'},...
    'String', '128.0.254.2',...
    'Position',[PosX_edit Pos+0.04 Length_edit Height_edit]);

% Bras port
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment',Alignement,...
    'position',[PosX_text Pos-0.16 0.15 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Port bras');

% Bras edit box
guiPRT.Bras = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame1_CB,num_figure,'Bras_ini'},...
    'String', '15',...
    'Position',[PosX_edit Pos-0.16+0.04 Length_edit Height_edit]);

% Numéro de voie de l'ocilloscope
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment',Alignement,...
    'position',[PosX_text Pos-(0.16*2.16) 0.2 0.14],...
    'BackgroundColor', PanelColor,...
    'String',['Num',char(233),'ro voie oscilloscope']);

% Voie de l'ocilloscope edit box
guiPRT.Oscillo = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame1_CB,num_figure,'Number_oscillo'},...
    'String', '2',...
    'Position',[PosX_edit Pos-(0.16*2)+0.04 Length_edit Height_edit]);

% Sensibilité hydrophone
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment',Alignement,...
    'position',[PosX_text Pos-(0.16*3.16) 0.2 0.14],...
    'BackgroundColor', PanelColor,...
    'String',['Sensibilit',char(233),' hydrophone [V/MPa]']);

% Sensibilité hydrophone edit box
guiPRT.Sensibility_hydro = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame1_CB,num_figure,'Sensibility_hydro'},...
    'String', '0.2501',...
    'Position',[PosX_edit Pos-(0.16*3)+0.04 Length_edit Height_edit]);

%%
Right_text = 0.51;
Right_pos = 0.63;
%%

% Pulse duration
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment',Alignement,...
    'position',[Right_text Pos-0.02 0.2 0.14],...
    'BackgroundColor', PanelColor,...
    'String','Pulse duration [s]');

% Pulse duration edit box
guiPRT.Pulse_duration = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame1_CB,num_figure,'Pulse_duration'},...
    'String', '1.92e-07',...
    'Position',[Right_pos Pos+0.04 Length_edit Height_edit]);

% Temperature
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment',Alignement,...
    'position',[Right_text Pos-(0.16*1.16) 0.2 0.14],...
    'BackgroundColor', PanelColor,...
    'String','Temperature [°C]');

% Temperature edit box
guiPRT.Temperature = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame1_CB,num_figure,'Temperature'},...
    'String', '16',...
    'Position',[Right_pos Pos-(0.16*1)+0.04 Length_edit Height_edit]);

% PRF
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment',Alignement,...
    'position',[Right_text Pos-(0.16*2.16) 0.2 0.14],...
    'BackgroundColor', PanelColor,...
    'String','PRF [Hz]');

% PRF edit box
guiPRT.PRF = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame1_CB,num_figure,'PRF'},...
    'String', '333',...
    'Position',[Right_pos Pos-(0.16*2)+0.04 Length_edit Height_edit]);

%% ALIGNEMENT DU BRAS
% Bouton réinitialisation
guiPRT.Reset_button = uicontrol(guiPRT.framePanel_down,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'Visible','on',...
    'Enable','off',...
    'FontSize',11,...
    'position',[0.04 0.5 0.15 0.24],...
    'Callback',{@IHM_frame1_CB,num_figure,'Reset'},...
    'Value',0,...
    'String','Reset');

% Axe X
guiPRT.Axe_X = uicontrol(guiPRT.framePanel_down,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Enable','off',...
    'Callback',{@IHM_frame1_CB,num_figure,'Axe_X'},...
    'String', '0',...
    'Position',[0.23 0.51 0.1 0.16]);

% Axe X text
uicontrol(guiPRT.framePanel_down,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[0.23 0.7 0.1 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Axe X [mm]');

% Axe Y
guiPRT.Axe_Y = uicontrol(guiPRT.framePanel_down,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Enable','off',...
    'Callback',{@IHM_frame1_CB,num_figure,'Axe_Y'},...
    'String', '0',...
    'Position',[0.37 0.51 0.1 0.16]);

% Axe Y text
uicontrol(guiPRT.framePanel_down,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[0.37 0.7 0.1 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Axe Y [mm]');

% Axe Z
guiPRT.Axe_Z = uicontrol(guiPRT.framePanel_down,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Enable','off',...
    'Callback',{@IHM_frame1_CB,num_figure,'Axe_Z'},...
    'String', '0',...
    'Position',[0.51 0.51 0.1 0.16]);

% Axe Z text
uicontrol(guiPRT.framePanel_down,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[0.51 0.7 0.1 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Axe Z [mm]');

% Bouton deplacement
guiPRT.Move_button = uicontrol(guiPRT.framePanel_down,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'Visible','on',...
    'Enable','off',...
    'FontSize',11,...
    'position',[0.65 0.5 0.15 0.24],...
    'Callback',{@IHM_frame1_CB,num_figure,['D',char(233),'placement']},...
    'Value',0,...
    'String',['D',char(233),'placement']);

% Bouton Lancement
guiPRT.Lancement = uicontrol(guiPRT.framePanel_down,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'Visible','on',...
    'Enable','off',...
    'FontSize',11,...
    'position',[0.34 0.11 0.15 0.24],...
    'Callback',{@IHM_frame1_CB,num_figure,'Lancement'},...
    'Value',0,...
    'String','Lancement');

STRUCT_PRT.figure.frame1_up = guiPRT.framePanel_up;
STRUCT_PRT.figure.frame1_down = guiPRT.framePanel_down;
end