function [guiPRT] = IHM_frame2(STRUCT_PRT)
% *************************************************************************
%   Name :   IHM_frame2
%   Date of creation : 04/11/2021
%   Description : Creation of the menus in the main window
% *************************************************************************

Parent = STRUCT_PRT.figure.START.panel_ihm;
num_figure = STRUCT_PRT.figure.num_figure;
PanelColor = [0.815686274509804	0.878431372549020 0.921568627450980];
Off_sight = 'off';

%% Principal Panel
guiPRT.framePanel_up = uipanel(Parent,...
    'visible', 'off',...
    'BackgroundColor',PanelColor,...
    'Title', ('Definition of the beam axis'),...
    'FontSize',11,...
    'position',[0 0.6 1.*1/0.86 1-0.6]);

guiPRT.framePanel_down = uipanel(Parent,...
    'visible', 'off',...
    'BackgroundColor',PanelColor,...
    'Title', ('Graphics'),...
    'FontSize',11,...
    'position',[0 0 1.*1/0.86 0.6]);

%% Elements graphiques

PosX_edit = 0.38;

% Retour en arrière
guiPRT.Retour = uicontrol(guiPRT.framePanel_up,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'FontSize',11,...
    'position',[PosX_edit 0.56 0.15 0.25],...
    'Callback',{@IHM_frame2_CB,num_figure,'Retour'},...
    'Value',0,...
    'String',['Retour en arri',char(232),'re']);

% Exécuter
guiPRT.Execute = uicontrol(guiPRT.framePanel_up,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'FontSize',11,...
    'position',[PosX_edit 0.15 0.15 0.25],...
    'Callback',{@IHM_frame2_CB,num_figure,'Execute'},...
    'Value',0,...
    'String',['Ex',char(233),'cuter']);

Pos = 0.78;
PosX_edit = 0.01;

% Profondeur 2
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[PosX_edit Pos 0.15 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Profondeur 2 [mm]');

Length_edit = 0.12;

% Profondeur 2 edit box
guiPRT.Profondeur_2 = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame2_CB,num_figure,'Profondeur_2'},...
    'String', '0',...
    'Position',[PosX_edit+0.01 Pos-0.17 Length_edit 0.14]);

% Profondeur 3
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[PosX_edit Pos-0.44 0.15 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Profondeur 3 [mm]');

% Profondeur 3 edit box
guiPRT.Profondeur_3 = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame2_CB,num_figure,'Profondeur_3'},...
    'String', '0',...
    'Position',[PosX_edit+0.01 Pos-0.17-0.44 Length_edit 0.14]);

% Pas
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[PosX_edit+0.21 Pos 0.15 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Pas [mm]');

% Pas edit box
guiPRT.Pas = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame2_CB,num_figure,'Pas'},...
    'String', '0',...
    'Position',[PosX_edit+0.22 Pos-0.17 Length_edit 0.14]);

% Longueur de scan limite
uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible','on',...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[PosX_edit+0.21 Pos-0.44 0.15 0.12],...
    'BackgroundColor', PanelColor,...
    'String','Longueur limite [mm]');

% Longueur de scan limite edit box
guiPRT.Longueur_limite = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'Callback',{@IHM_frame2_CB,num_figure,'Longueur_limite'},...
    'String', '0',...
    'Position',[PosX_edit+0.22 Pos-0.17-0.44 Length_edit 0.14]);

% Reset
guiPRT.Reset = uicontrol(guiPRT.framePanel_up,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'FontSize',11,...
    'position',[PosX_edit+0.13 Pos-0.41 0.09 0.2],...
    'Callback',{@IHM_frame2_CB,num_figure,'Reset'},...
    'Value',0,...
    'String','Reset');

%% Graphics part
guiPRT.Graphics_Acoustic = axes(guiPRT.framePanel_down,...
    'units','normalized',...
    'Visible','on',...
    'OuterPosition',[0 0 1-0.55 1]);

guiPRT.Graphics_Middle_Pos = axes(guiPRT.framePanel_down,...
    'units','normalized',...
    'Visible','on',...
    'OuterPosition',[1-0.6 0 1-0.55 1]);

%% ISPTA edit box
Posx = 0.55;
Posy = 0.8;
% Text
guiPRT.ISPTA_text = uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible', Off_sight,...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[Posx-0.01 Posy-0.04 0.10 0.12],...
    'BackgroundColor', PanelColor,...
    'String','ISPTA [W/m²]');

% Edit box
guiPRT.ISPTA = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'Visible', Off_sight,...
    'Enable', 'inactive',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'String', '',...
    'Position',[Posx Posy-0.24 0.08 0.22]);

%% Mechanical index edit box
Posy = 0.35;
% Text
guiPRT.MI_text = uicontrol(guiPRT.framePanel_up,...
    'style', 'text',...
    'Units','normalized',...
    'Visible', Off_sight,...
    'FontSize',11,...
    'HorizontalAlignment','Center',...
    'position',[Posx Posy 0.08 0.12],...
    'BackgroundColor', PanelColor,...
    'String','MI');

% Edit box
guiPRT.MI = uicontrol(guiPRT.framePanel_up,...
    'style','edit',...
    'units','normalized',...
    'Visible', Off_sight,...
    'Enable', 'inactive',...
    'FontSize',11,...
    'BackgroundColor','w',...
    'String', '',...
    'Position',[Posx Posy-0.19 0.08 0.22]);

%%
Posx = 0.66;

% White rectangle
guiPRT.Rectangle = uicontrol(guiPRT.framePanel_up,...
    'style','text',...
    'units','normalized',...
    'FontSize',9,...
    'BackgroundColor','white',...
    'Position',[Posx+0.02 0.55 0.1 0.25]);

% Suivant ("Next")
guiPRT.Suivant = uicontrol(guiPRT.framePanel_up,...
    'style', 'pushbutton',...
    'Units','normalized',...
    'FontSize',11,...
    'position',[Posx 0.15 0.15 0.25],...
    'Enable', Off_sight,...
    'Callback',{@IHM_frame2_CB,num_figure,'Suivant'},...
    'Value',0,...
    'String','Suivant');

STRUCT_PRT.figure.frame2_up = guiPRT.framePanel_up;
STRUCT_PRT.figure.frame2_down = guiPRT.framePanel_down;
end